# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Deploy
on: push

jobs:
  deploy:
    uses: ./.github/workflows/deploy-workflow-call.yml
    with:
      test: "Deploy Super"
