on:
  workflow_call:
    inputs:
      test:
        type: string
        required: true


jobs:
  test:
    name: ${{ inputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: echo ${{ inputs.test }}

  test-bis:
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: echo ${{ inputs.test }}

  test-tres:
    needs: test-bis
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: echo ${{ inputs.test }}